[package]
name = "pocket-cube-prob"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
num-traits = "0.2.18"
rand = "0.8.5"
three-d = "0.17.0"
three-d-asset = "0.7.0"
three-d-text-builder = "0.7.0"
